[package]
name = "onn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
ndarray = "0.15.6"
ort = "1.14.8"
serde = "1.0.164"
tokenizers = "0.13.3"
